In [1]:
import numpy as np
#Uno de sus usos es para trabajar con matrices 

In [3]:
valoraciones = np.array([[8,7,8,5], [2,6,8,1], [8,8,9,5]])
valoraciones

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

In [4]:
#Para acceder a los datos 
valoraciones [0][0]

8

In [6]:
#También se puede acceder así:
valoraciones [0,0]

8

In [9]:
valoraciones2 = np.array([[[8,7,8,5], [2,5,5,2]], [[2,6,8,4], [8,8,9,3]], [[10,9,10,8], [1,2,3,4]]])

In [11]:
valoraciones2

array([[[ 8,  7,  8,  5],
        [ 2,  5,  5,  2]],

       [[ 2,  6,  8,  4],
        [ 8,  8,  9,  3]],

       [[10,  9, 10,  8],
        [ 1,  2,  3,  4]]])

In [18]:
valoraciones2[0,1,3]

2

In [19]:
#Podemos crear arrays vacios
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [21]:
#Podemos hacer operaciones entre arrays
#En este caso, sumamos 1 
valoraciones2 + np.ones((3,2,4))

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  6.,  6.,  3.]],

       [[ 3.,  7.,  9.,  5.],
        [ 9.,  9., 10.,  4.]],

       [[11., 10., 11.,  9.],
        [ 2.,  3.,  4.,  5.]]])

In [22]:
#También podemos palicar otras funciones, como sacar su media
np.mean(valoraciones)

6.25

In [23]:
#Podemos calcular la media de sus distintos ejes 
np.mean(valoraciones2, axis=0)

array([[6.66666667, 7.33333333, 8.66666667, 5.66666667],
       [3.66666667, 5.        , 5.66666667, 3.        ]])

In [24]:
np.mean(valoraciones2, axis=1)

array([[5. , 6. , 6.5, 3.5],
       [5. , 7. , 8.5, 3.5],
       [5.5, 5.5, 6.5, 6. ]])

In [25]:
np.mean(valoraciones2, axis=2)

array([[7.  , 3.5 ],
       [5.  , 7.  ],
       [9.25, 2.5 ]])

In [26]:
#reshape nos permite convertir una lista a un array con las dimensiones que indiquemos
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12], (3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
# np.median nos da la mediana
np.median(df["Columna1"])

In [29]:
# np.randopm nos permite generar objetos aleatorios
np.random.rand(2,2)

array([[0.63350806, 0.31207096],
       [0.82181365, 0.93604272]])